/**
 * Gecko auto-setup orchestrator.
 *
 * After `docker compose up`, this:
 *   1. Configures Jellyfin (startup wizard — no equivalent container)
 *   2. Configures qBittorrent (password change on first boot)
 *   3. Reads API keys generated by linuxserver/*arr images from config.xml
 *   4. Writes API keys to .env so the container-side init.py can use them
 *   5. Invokes `docker compose --profile init up gecko-init` — a one-shot
 *      Python container that handles root folders, download clients,
 *      Prowlarr↔apps sync, Bazarr↔*arrs links, and Jellyseerr setup
 *      (idempotent — safe to re-run)
 *   6. Triggers `recyclarr sync` to apply TRaSH Guides quality profiles
 *
 * Previous version (~670 lines) did everything in TS via HTTP. Replaced because:
 *   - Sonarr v4 / Radarr v5 API drift kept breaking the inline payloads
 *   - Bazarr/Jellyseerr flows were fragile and hard to retry independently
 *   - Container-side scripts are easier to debug (clear stdout, isolated env)
 */
import http from 'node:http';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';

const execAsync = promisify(exec);
const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

// ── Retry with exponential backoff ───────────────────────────────────

async function withRetry<T>(fn: () => Promise<T>, attempt = 1, maxAttempts = 5): Promise<T> {
  try {
    return await fn();
  } catch (err) {
    if (attempt >= maxAttempts) throw err;
    await sleep(2 ** (attempt - 1) * 1000);
    return withRetry(fn, attempt + 1, maxAttempts);
  }
}

// ── HTTP primitives (only used for Jellyfin/qBit — *arrs are handled by init.py) ──

type Resp = { status: number; body: string; cookies: string[] };

function httpRequest(opts: http.RequestOptions, body?: string): Promise<Resp> {
  return new Promise(resolve => {
    const fail = () => resolve({ status: 0, body: '', cookies: [] });
    const req = http.request(opts, res => {
      let data = '';
      res.on('data', (d: Buffer) => data += d);
      res.on('end', () => {
        const cookies = (res.headers['set-cookie'] ?? []) as string[];
        resolve({ status: res.statusCode ?? 0, body: data, cookies });
      });
    });
    req.on('error', fail);
    req.setTimeout(10000, () => { req.destroy(); fail(); });
    if (body) req.write(body);
    req.end();
  });
}

function jsonPost(port: number, path: string, body: object, extraHeaders: Record<string, string> = {}): Promise<Resp> {
  const data = JSON.stringify(body);
  return httpRequest({
    hostname: 'localhost', port, path, method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': String(Buffer.byteLength(data)),
      ...extraHeaders,
    },
  }, data);
}

function formPost(port: number, path: string, formBody: string, extraHeaders: Record<string, string> = {}): Promise<Resp> {
  return httpRequest({
    hostname: 'localhost', port, path, method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'Content-Length': String(Buffer.byteLength(formBody)),
      'Referer': `http://localhost:${port}`,
      ...extraHeaders,
    },
  }, formBody);
}

async function waitReady(port: number, path: string, maxWaitSecs = 180): Promise<boolean> {
  const attempts = Math.ceil(maxWaitSecs / 5);
  for (let i = 0; i < attempts; i++) {
    const { status } = await httpRequest({ hostname: 'localhost', port, path });
    if (status > 0 && status < 500) return true;
    await sleep(5000);
  }
  return false;
}

// ── Jellyfin (no container equivalent — must do startup wizard via API) ──

async function configureJellyfin(port: number, adminPassword: string): Promise<void> {
  const ready = await waitReady(port, '/Startup/Configuration', 180);
  if (!ready) throw new Error('Jellyfin not ready');

  const check = await httpRequest({ hostname: 'localhost', port, path: '/Startup/Configuration' });
  if (check.status !== 200) return; // wizard already complete

  const cfg1 = await jsonPost(port, '/Startup/Configuration', {
    UICulture: 'en-US', MetadataCountryCode: 'US', PreferredMetadataLanguage: 'en',
  });
  if (cfg1.status < 200 || cfg1.status >= 300) throw new Error(`Startup/Configuration: ${cfg1.status}`);

  await jsonPost(port, '/Startup/RemoteAccess', {
    EnableRemoteAccess: true, EnableAutomaticPortMapping: false,
  });

  const cfg3 = await jsonPost(port, '/Startup/User', {
    Name: 'admin', Password: adminPassword,
  });
  if (cfg3.status < 200 || cfg3.status >= 300) {
    throw new Error(`Startup/User: ${cfg3.status} — ${cfg3.body.slice(0, 200)}`);
  }

  await jsonPost(port, '/Startup/Complete', {});
  await sleep(4000);

  // Post-wizard: rename server, enable legacy auth for Jellyseerr compatibility.
  // Best-effort; failures here don't break the install.
  try {
    const mediaAuth = 'MediaBrowser Client="Gecko", Device="Setup", DeviceId="gecko-setup-v1", Version="1.0"';
    const authResp = await jsonPost(port, '/Users/AuthenticateByName',
      { Username: 'admin', Pw: adminPassword },
      { Authorization: mediaAuth });
    if (authResp.status !== 200) return;
    const { AccessToken } = JSON.parse(authResp.body) as { AccessToken: string };
    const authHeaders = { Authorization: `MediaBrowser Token="${AccessToken}"` };

    const cfgResp = await httpRequest({ hostname: 'localhost', port, path: '/System/Configuration', headers: authHeaders });
    if (cfgResp.status === 200) {
      const sysCfg = JSON.parse(cfgResp.body) as Record<string, unknown>;
      sysCfg.ServerName = 'Gecko';
      const body = JSON.stringify(sysCfg);
      await httpRequest({
        hostname: 'localhost', port, path: '/System/Configuration', method: 'POST',
        headers: { ...authHeaders, 'Content-Type': 'application/json', 'Content-Length': String(Buffer.byteLength(body)) },
      }, body);
    }

    const netResp = await httpRequest({ hostname: 'localhost', port, path: '/System/Configuration/Network', headers: authHeaders });
    if (netResp.status === 200) {
      const netCfg = JSON.parse(netResp.body) as Record<string, unknown>;
      netCfg.EnableLegacyAuthorization = true;
      const body = JSON.stringify(netCfg);
      await httpRequest({
        hostname: 'localhost', port, path: '/System/Configuration/Network', method: 'POST',
        headers: { ...authHeaders, 'Content-Type': 'application/json', 'Content-Length': String(Buffer.byteLength(body)) },
      }, body);
    }
  } catch { /* best-effort */ }
}

// ── qBittorrent (linuxserver image prints temp password on first boot) ──

async function qbitTempPassword(dockerEnvObj: NodeJS.ProcessEnv): Promise<string | null> {
  try {
    const { stdout } = await execAsync('docker logs media_qbittorrent 2>&1', { env: dockerEnvObj });
    const m = stdout.match(/temporary password[^:]*:\s*([A-Za-z0-9]+)/i);
    return m?.[1] ?? null;
  } catch { return null; }
}

async function qbitLogin(port: number, password: string): Promise<string | null> {
  const body = `username=admin&password=${encodeURIComponent(password)}`;
  const resp = await formPost(port, '/api/v2/auth/login', body);
  if (resp.body.trim() !== 'Ok.') return null;
  const cookie = resp.cookies.find(c => c.startsWith('SID='));
  return cookie?.match(/SID=([^;]+)/)?.[1] ?? null;
}

async function configureQbit(port: number, adminPassword: string, dockerEnvObj: NodeJS.ProcessEnv): Promise<void> {
  const ready = await waitReady(port, '/api/v2/app/version', 120);
  if (!ready) throw new Error('qBittorrent not ready');

  let sid = await qbitLogin(port, adminPassword);
  if (!sid) {
    const tempPass = await qbitTempPassword(dockerEnvObj);
    if (tempPass) {
      sid = await qbitLogin(port, tempPass);
      if (sid) {
        const chg = JSON.stringify({ web_ui_password: adminPassword });
        await formPost(port, '/api/v2/app/setPreferences', `json=${encodeURIComponent(chg)}`, { Cookie: `SID=${sid}` });
        await sleep(2000);
        sid = await qbitLogin(port, adminPassword);
      }
    }
  }
  if (!sid) throw new Error('qBittorrent login failed');

  const prefs = JSON.stringify({ save_path: '/downloads' });
  await formPost(port, '/api/v2/app/setPreferences', `json=${encodeURIComponent(prefs)}`, { Cookie: `SID=${sid}` });
}

// ── *arr API key lookup (linuxserver images generate on first boot) ──

async function readArrApiKey(containerName: string, dockerEnvObj: NodeJS.ProcessEnv): Promise<string> {
  for (let i = 0; i < 12; i++) {
    try {
      const { stdout } = await execAsync(`docker exec ${containerName} cat /config/config.xml`, { env: dockerEnvObj });
      const m = stdout.match(/<ApiKey>([a-zA-Z0-9]+)<\/ApiKey>/);
      if (m?.[1]) return m[1];
    } catch { /* container not ready yet */ }
    await sleep(5000);
  }
  throw new Error(`Could not read API key from ${containerName}`);
}

async function readBazarrApiKey(dockerEnvObj: NodeJS.ProcessEnv): Promise<string> {
  for (let i = 0; i < 12; i++) {
    try {
      let raw = '';
      try {
        const { stdout } = await execAsync('docker exec media_bazarr cat /config/config/config.yaml', { env: dockerEnvObj });
        raw = stdout;
      } catch { /* try .ini */ }
      if (!raw.match(/apikey/i)) {
        const { stdout } = await execAsync('docker exec media_bazarr cat /config/config/config.ini', { env: dockerEnvObj });
        raw = stdout;
      }
      const m = raw.match(/apikey[:\s=]+([a-f0-9]{32,})/i);
      if (m?.[1]) return m[1];
    } catch { /* retry */ }
    await sleep(5000);
  }
  throw new Error('Could not read Bazarr API key');
}

// ── .env writer (so gecko-init container picks up the keys) ──────────

async function writeEnvKeys(envPath: string, keys: Record<string, string>): Promise<void> {
  let current = '';
  try { current = await fs.readFile(envPath, 'utf8'); } catch { /* new file */ }
  const lines = current.split('\n');
  for (const [k, v] of Object.entries(keys)) {
    const idx = lines.findIndex(l => l.startsWith(`${k}=`));
    if (idx >= 0) lines[idx] = `${k}=${v}`;
    else lines.push(`${k}=${v}`);
  }
  await fs.writeFile(envPath, lines.join('\n'), 'utf8');
}

// ── Run the gecko-init container (does everything else) ──────────────

async function runGeckoInit(stackDir: string, dockerEnvObj: NodeJS.ProcessEnv): Promise<string[]> {
  const { stdout, stderr } = await execAsync(
    'docker compose --profile init up --build --abort-on-container-exit gecko-init',
    { cwd: stackDir, env: dockerEnvObj, maxBuffer: 1024 * 1024 * 10 },
  );
  // Surface stdout for the UI — every "[Sonarr] root /tv: created" line ends up here.
  console.log('[gecko-init]', stdout);
  if (stderr && !stderr.match(/^Creating|^Starting|^Building|^\s*$/m)) {
    console.warn('[gecko-init stderr]', stderr);
  }
  // init.py exits 0 even when steps SKIP (degraded paths the user can finish
  // in the UI). Those would otherwise be invisible — extract them so the
  // wizard can show a "finish this manually" note instead of a false 100%.
  return stdout
    .split('\n')
    .map(l => l.trim())
    .filter(l => l.includes('SKIP'));
}

// ── Trigger Recyclarr sync (also idempotent) ─────────────────────────

async function runRecyclarrSync(stackDir: string, dockerEnvObj: NodeJS.ProcessEnv): Promise<void> {
  await execAsync('docker compose exec -T recyclarr recyclarr sync', {
    cwd: stackDir, env: dockerEnvObj, maxBuffer: 1024 * 1024 * 5,
  });
}

// ── Public API ───────────────────────────────────────────────────────

export interface AutoSetupConfig {
  adminPassword: string;
  subtitleLangs: string[];
  ports: {
    jellyfin: number; radarr: number; sonarr: number; lidarr: number;
    prowlarr: number; bazarr: number; qbit: number; jellyseerr: number;
  };
  vpnEnabled: boolean;
  stackDir: string;             // path to ./stack — where docker-compose.yml lives
  dockerEnvObj: NodeJS.ProcessEnv;
  onProgress: (step: number) => void;
  onStepFailed?: (step: number) => void;
}

export async function runAutoSetup(cfg: AutoSetupConfig): Promise<{
  failedSteps: Array<{ step: number; error: string }>;
  skips: string[];
  apiKeys: { radarr: string; sonarr: string; lidarr: string; prowlarr: string; bazarr: string };
}> {
  const { adminPassword, subtitleLangs, ports, vpnEnabled, stackDir, dockerEnvObj,
          onProgress, onStepFailed } = cfg;
  const failedSteps: Array<{ step: number; error: string }> = [];
  const skips: string[] = [];
  const apiKeys = { radarr: '', sonarr: '', lidarr: '', prowlarr: '', bazarr: '' };

  const tryStep = async (step: number, fn: () => Promise<void>) => {
    onProgress(step);
    try {
      await withRetry(fn);
    } catch (err) {
      const error = err instanceof Error ? err.message : String(err);
      failedSteps.push({ step, error });
      onStepFailed?.(step);
    }
  };

  // Step 3: Jellyfin wizard
  await tryStep(3, () => configureJellyfin(ports.jellyfin, adminPassword));

  // Step 4: qBittorrent password
  await tryStep(4, () => configureQbit(ports.qbit, adminPassword, dockerEnvObj));

  // Step 5: read API keys from config.xml of each *arr (linuxserver auto-generates them)
  await tryStep(5, async () => {
    [apiKeys.radarr, apiKeys.sonarr, apiKeys.lidarr, apiKeys.prowlarr, apiKeys.bazarr] = await Promise.all([
      readArrApiKey('media_radarr', dockerEnvObj),
      readArrApiKey('media_sonarr', dockerEnvObj),
      readArrApiKey('media_lidarr', dockerEnvObj),
      readArrApiKey('media_prowlarr', dockerEnvObj),
      readBazarrApiKey(dockerEnvObj),
    ]);
    await writeEnvKeys(path.join(stackDir, '.env'), {
      RADARR_API_KEY: apiKeys.radarr,
      SONARR_API_KEY: apiKeys.sonarr,
      LIDARR_API_KEY: apiKeys.lidarr,
      PROWLARR_API_KEY: apiKeys.prowlarr,
      BAZARR_API_KEY: apiKeys.bazarr,
      ADMIN_PASSWORD: adminPassword,
      SUBTITLE_LANGS: subtitleLangs.join(','),
      QBIT_HOST: vpnEnabled ? 'media_gluetun' : 'media_qbittorrent',
    });
  });

  // Step 6: gecko-init container does root folders, download clients,
  // Prowlarr↔apps, Bazarr↔*arrs, Jellyseerr setup — all in one shot.
  await tryStep(6, async () => {
    const initSkips = await runGeckoInit(stackDir, dockerEnvObj);
    skips.push(...initSkips);
  });

  // Step 7: Recyclarr applies TRaSH Guides quality profiles & custom formats.
  await tryStep(7, () => runRecyclarrSync(stackDir, dockerEnvObj));

  return { failedSteps, skips, apiKeys };
}
